<div align="right">
  <img src="https://drive.google.com/uc?export=view&id=1J8JpP65HsHXdpJvhb_sMwn3yROyU832m" height="80" width="200" style="float: right;">
</div>
<h1><b>Data Science and Machine Learning</b></h1>
<h2><b>Clase 1</b>: Prework Review - Parte 1</h2>
<h3><b>Docente</b>: <a href="https://www.linkedin.com/in/danielablanco/">Daniela Blanco</a>

# Contenido

- [1. Terminología básica](#terminologia)
- [2. Python](#python)
  - [2.1 Variables](#variables)
  - [2.2 Tipos de datos](#tipos_de_datos)
  - [2.3 Operadores](#operadores)
  - [2.4 Estructuras de control](#estructuras)      
  - [2.5 Funciones](#funciones)
  - [2.6 Librerías](#librerias)  
- [3. Numpy](#numpy)
- [4. Actividad Numpy](#proyecto)

## 1. Terminología básica <a name="terminologia"></a>

<img src="https://drive.google.com/uc?export=view&id=1rwkyvWbw_5-lDSrle_ZdQ3fX7RHxzM5R" height="330" width="500" style="float: center;">

<b>Inteligencia Artificial (IA)</b>

- Campo de estudio que se enfoca en cómo hacer que las computadoras piensen y actúen como los humanos.
- Incluye subcampos, como el aprendizaje automático, la robótica, el procesamiento del lenguaje natural, la visión por computadora...

<b>Machine learning (ML)</b>

- Es un subcampo de la IA que se centra en desarrollar algoritmos y modelos que permitan a las computadoras aprender a partir de datos. Sin ser programadas explícitamente para cada tarea.
- El machine learning se divide en dos categorías principales: aprendizaje supervisado (donde se proporcionan datos etiquetados) y aprendizaje no supervisado (donde se buscan patrones en datos no etiquetados).

<b>Deep Learning / Apendizaje profundo</b>

- Son técnicas de machine learning que utilizan principalmente redes neuronales para aprender automáticamente características y patrones complejos a partir de datos.
- Ha demostrado ser especialmente eficaz en tareas como el reconocimiento de imágenes y de voz, el procesamiento del lenguaje natural y la toma de decisiones basadas en datos complejos.

<b>Ciencia de Datos</b>

- Es un campo interdisciplinario que se centra en la extracción de conocimiento a partir de grandes volumenes de datos.
- Utiliza técnicas estadísticas, informáticas y de análisis para interpretar, comprender y extraer conocimiento.
-	Incluye la adquisición, limpieza, análisis y visualización de datos, y puede hacer uso de la IA y del machine learning para analizarlos.

## 2. Python <a name="python"></a>

- Lenguaje de programación muy versátil.
- El más utilizado para trabajar con datos y principalmente en ciencia de datos.

### 2.1 Variables <a name="variables"></a>

|  | |
|--|--|
| <img src="https://drive.google.com/uc?export=view&id=193nwbWQowZ2Ev726kmYqZ7u6BSKTBvfP" height="120" width="200" style="float: center;">  | <p>Contenedor para almacenar un valor que puede variar en el tiempo.</p> <p>Tiene un nombre propio (buena práctica que sea declarativo).</p><p>Cada variable tendrá además un tipo de datos.</p>|

In [3]:
nombre = "Juan"
edad = 25
altura = 1.80
es_estudiante = True

In [2]:
nombre

'Juan'

In [4]:
print(edad)

25


### 2.2 Tipos de datos <a name="tipos_de_datos"></a>

Los tipos de datos (data types) determinan la clase de datos que una variable puede contener.

### Tipos básicos

Python, como todos los lenguajes de programación, tiene sus propios tipos básicos:
- Enteros (int): Representa números enteros, positivos o negativos.
- Punto flotante (float): Representa números reales con decimales.
- Cadena de carácteres (string): Representa secuencias de caracteres (texto).
- Booleano (bool): Representa valor de verdad, True o False.

In [5]:
num_int = 123
num_float = 3.14
str_var = 'Esto es un texto de prueba'
bool_var = True

In [6]:
type(num_int)

int

In [7]:
type(num_float)

float

In [8]:
type(str_var)

str

In [9]:
type(bool_var)

bool

### Tipos compuestos *

Tipos de datos que permiten tener colecciones de elementos.

- Listas (list): colección ordenada de elementos. Los elementos pueden ser de cualquier tipo y se puede modificar su contenido
- Tuplas (tuple) Similar a la lista, pero es inmutable, es decir, una vez creada no se puede modificar su contenido.
- Diccionario (dictionary):  colección no ordenada de pares clave-valor.

*No son los únicos, pero si los más utilizados en ciencia de datos.

In [10]:
list_numbers = [1, True, 'hola', 4, 5]

tuple_numbers = (1, 2, 3, 4, 5)

dict_person = {
    "nombre": "Juan",
    "edad": 25,
    "altura": 1.80,
    "es_estudiante": True
}

### 2.3 Operadores <a name="operadores"></a>

Son símbolos que indican una operación.

- Matemáticos: realizan operaciones aritméticas. Aunque dependiendo del tipo de las variables, los resultados pueden no ser numéricos (python implementó el mismo símbolo para varios usos).

In [ ]:
# Suma
x = 5
y = 3

z = x + y
z

In [ ]:
# Resta
x = 5
y = 3

z = x - y
z

In [ ]:
# Multiplicación
x = 5
y = 3

z = x * y
z

In [ ]:
# División
x = 5
y = 3

z = x / y
z

In [11]:
# Módulo
x = 5
y = 3

z = x % y
z

2

In [12]:
# Suma cadenas
x = 'Hola'
y = 'primera clase!'

z = x + y
z

'Holaprimera clase!'

- Lógicos: evalúan condiciones y devuelven valores booleanos. Son muy versátiles y útiles.

In [ ]:
# Y
resultado = True and False
resultado

In [ ]:
# O
resultado = True or False
resultado

In [ ]:
# Negación
resultado = not False
resultado

### 2.4 Estructuras de control <a name="estructuras"></a>

Instrucciones que permiten modificar el flujo de ejecución secuencial de un programa.

Estas estructuras permiten tomar decisiones, repetir bloques de código y saltar a diferentes partes del código dependiendo de ciertas condiciones lógicas.

Al combinarlas y anidarlas, podemos crear flujos de trabajo complejos y lógicas sofisticadas en nuestros programas.

* Condicionales: Permite ejecutar un bucle de código si se cumple una condición.

In [16]:
edad = 18

if edad >= 18:
    print("Eres mayor de edad.")
print('Termino')

Eres mayor de edad.
Termino


In [ ]:
edad = 18

if edad < 18:
    print("Eres menor de edad.")
else:
    print("Eres mayor de edad.")

* FOR: Repite un bloque de código un número determinado de veces o a través de los elementos de una colección.

In [17]:
for i in range(5):
    print(i)

0
1
2
3
4


In [18]:
frutas = ["manzana", "banana", "cereza"]

for fruta in frutas:
    print(fruta)

manzana
banana
cereza


* WHILE: Repite un bloque de código mientras se cumpla una condición.

In [19]:
contador = 0

while contador < 5:
    print(contador)
    contador += 1

0
1
2
3
4


* Instrucciones para control de ciclos

In [ ]:
for letra in "Python":
    if letra == "h":
        # Termina el bucle antes de que haya completado todas sus iteraciones.
        break
    print(letra)

In [ ]:
for letra in "Python":
    if letra == "h":
        # Salta a la siguiente iteración del bucle, omitiendo el código que sigue después.
        continue
    print(letra)

### 2.5 Funciones <a name="funciones"></a>

Es un bloque de código reutilizable que realiza una tarea específica.
Tendrá un nombre propio.

Puede (o no) recibir parámetros.

Las funciones proporcionan una forma de modularizar el código, permitiéndonos organizar y reutilizar fragmentos de código en diferentes partes de nuestros programas. Esto mejora la calidad y facilita la depuración y el mantenimiento.

In [20]:
print(x)

Hola


In [21]:
def sumar_numeros(numero1, numero2):
    respuesta = numero1 + numero2

    return respuesta

In [23]:
rta = sumar_numeros(10, 6)

In [24]:
rta

16

### 2.6 Librerías <a name="librerias"></a>

<img src="https://drive.google.com/uc?export=view&id=1V8qB-9SiGg-KSZ0eLCgl_AuTvh4PPSZ_" height="120" width="600" style="float: center;">

Colección de funciones predefinidas y que se realizan con un fin determinado.

El objetivo es simplificar el trabajo del desarrollador y no tenerlas que programar desde cero.

Tienen mucha comunidad y mantenimiento.

Algunas de las librerías más utilizadas:
- Scikit-learn
- NumPy
- Pandas
- TensorFlow
- Keras
- Matplotlib
- Seaborn

## 3. Numpy <a name="numpy"></a>

<img src="https://drive.google.com/uc?export=view&id=1g3AUZk28Ku_gIejQbO8wzWHTWsSCgKhK" height="100" width="400" style="float: center;">

Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia.

Ventajas

- **Array multidimensionales**: agrega el tipo de datos `ndarray`, que permite almacenar y manipular grandes conjuntos de datos de forma eficiente. Los arrays pueden tener cualquier número de dimensiones.
- **Operaciones Vectorizadas**: permite realizar operaciones matemáticas en arrays completos sin la necesidad de bucles explícitos en el código, lo que lo hace muy rápido y eficiente.
- **Funciones matemáticas**: proporciona una amplia gama de funciones matemáticas para trabajar con arrays.
- **Eficiencia**: Es mucho más rápido que la misma funcionalidad implementada directamente sobre Python nativo.

In [25]:
import numpy as np

### Arrays de Numpy

Es una estructura de datos que permite almacenar una colección de elementos del mismo tipo.

- Array unidimensional: Es similar a una lista en Python, pero con las ventajas de rendimiento y funcionalidad que ofrece NumPy.

Podemos acceder a los elementos usando índices (indexes), modificarlos y realizar operaciones matemáticas en el array completo de forma eficiente.

In [26]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [28]:
# Acceder al tercer elemento
array[2]

3

In [29]:
# Cambiar el valor del segundo elemento
array[1] = 7
array


array([1, 7, 3, 4, 5])

In [30]:
# Sumar 10 a todos los elementos
array += 10
array

array([11, 17, 13, 14, 15])

In [31]:
# Calcular la suma de los elementos
sum_all = np.sum(array)
sum_all

70

- Array N-dimensional: estructura de datos que organiza elementos en múltiples dimensiones (ejes): matrices (array 2D, 2 ejes), tensores (array 3D, 3 ejes) y estructuras de mayor dimensión.

Son accesibles mediante índices al igual que los 1D.

In [33]:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [32]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Funciones

NumPy proporciona una gran cantidad de funciones predefinidas y que se pueden aplicar directamente sobre las estructuras de datos vistas anteriormente o las propias de Python (listas, matrices, etcétera).

In [35]:
# Crear un array para el ejemplo
arr = np.array([1, 2, 3, 4, 5])

In [36]:
# Operaciones Aritméticas
print(arr)
print("Suma:", np.add(arr, 5))
print("Producto:", np.multiply(arr, 3))

[1 2 3 4 5]
Suma: [ 6  7  8  9 10]
Producto: [ 3  6  9 12 15]


In [ ]:
# Logarítmicas y Exponenciales
print(arr)
print("Logaritmo natural:", np.log(arr))
print("Exponencial:", np.exp(arr))

In [37]:
# Funciones Estadísticas
print(arr)
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))
print("Varianza:", np.var(arr))
print("Máximo valor:", np.max(arr))
print("Índice del máximo valor:", np.argmax(arr))
print("Mínimo valor:", np.min(arr))
print("Índice del mínimo valor:", np.argmin(arr))
print("Suma de todos los elementos:", np.sum(arr))

[1 2 3 4 5]
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Máximo valor: 5
Índice del máximo valor: 4
Mínimo valor: 1
Índice del mínimo valor: 0
Suma de todos los elementos: 15


In [38]:
# Funciones de Redondeo
print(arr)
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print("Redondeo:", np.around(arr_decimal))
print("Entero menor (floor):", np.floor(arr_decimal))
print("Entero mayor (ceil):", np.ceil(arr_decimal))

[1 2 3 4 5]
Redondeo: [1. 2. 4. 5.]
Entero menor (floor): [1. 2. 3. 4.]
Entero mayor (ceil): [2. 3. 4. 5.]


## 4. Actividad Numpy <a name="proyecto"></a>

**1. Crea un array de NumPy que contenga las temperaturas diarias (en grados Celsius) de una ciudad durante una semana (7 días).**

**2. Accede y muestra la temperatura del tercer día de la semana y la temperatura del último día de la semana.**

**3. Calcula y muestra la temperatura promedio de la semana.**

**4. Encuentra y muestra la temperatura máxima y mínima registrada durante la semana.**

**5. Calcula un nuevo array que contenga la diferencia de temperatura entre días consecutivos de la semana. Ver método diff.**

**6. Supongamos que todas las temperaturas registradas estaban subestimadas por un error en el sensor y que hay que ajustarlas sumando 2 grados a cada temperatura. Calcula el nuevo array con las temperaturas corregidas.**

**7. Normaliza el array de temperaturas para que sus valores estén en el rango [0, 1]. La normalización se hace restando el mínimo valor y dividiendo por el rango (máximo - mínimo).**

**8. Escribe una función que reciba el array de temperaturas y un umbral (por ejemplo, 22°C) y devuelva un nuevo array con los días (índices) donde la temperatura fue superior al umbral.**

**9. Escribe una función que reemplace todas las temperaturas que están por debajo de un umbral (por ejemplo, 20°C) con el valor del umbral. La función debe devolver el nuevo array modificado.**

**10. Escribe una función que reciba el array de temperaturas y un porcentaje, y devuelva un nuevo array con las temperaturas incrementadas en ese porcentaje.**